server:
  servlet:
    context-path: /ifood/api


spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}/ifood?createDatabaseIfNotExist=true&serverTimezone=UTC
    username:
    password:
    driverClassName: com.mysql.jdbc.Driver

ifood:
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO:15}
    chave: ${JWT_CHAVE:123456}

